


<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html id="htmlId">
<head>
  <title>Coverage Report :: ExpectException</title>
  <style type="text/css">
    @import "../../.css/coverage.css";
  </style>
</head>

<body>
<div class="header"></div>

<div class="content">
<div class="breadCrumbs">
    [ <a href="../../index.html">all classes</a> ]
    [ <a href="../index.html">org.junit.internal.runners.statements</a> ]
</div>

<h1>Coverage Summary for Class: ExpectException (org.junit.internal.runners.statements)</h1>

<table class="coverageStats">
<tr>
  <th class="name">Class</th>
<th class="coverageStat 
">
  Class, %
</th>
<th class="coverageStat 
">
  Method, %
</th>
<th class="coverageStat 
">
  Line, %
</th>
</tr>
<tr>
  <td class="name">ExpectException</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 1)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 2)
  </span>
</td>
<td class="coverageStat">
  <span class="percent">
    0%
  </span>
  <span class="absValue">
    (0/ 17)
  </span>
</td>
</tr>

</table>

<br/>
<br/>


<div class="sourceCode"><i>1</i>&nbsp;//
<i>2</i>&nbsp;// Source code recreated from a .class file by IntelliJ IDEA
<i>3</i>&nbsp;// (powered by Fernflower decompiler)
<i>4</i>&nbsp;//
<i>5</i>&nbsp;
<i>6</i>&nbsp;package org.junit.internal.runners.statements;
<i>7</i>&nbsp;
<i>8</i>&nbsp;import org.junit.internal.AssumptionViolatedException;
<i>9</i>&nbsp;import org.junit.runners.model.Statement;
<b class="nc"><i>10</i>&nbsp;</b>
<b class="nc"><i>11</i>&nbsp;public class ExpectException extends Statement {</b>
<b class="nc"><i>12</i>&nbsp;    private final Statement next;</b>
<b class="nc"><i>13</i>&nbsp;    private final Class&lt;? extends Throwable&gt; expected;</b>
<i>14</i>&nbsp;
<i>15</i>&nbsp;    public ExpectException(Statement next, Class&lt;? extends Throwable&gt; expected) {
<i>16</i>&nbsp;        this.next = next;
<b class="nc"><i>17</i>&nbsp;        this.expected = expected;</b>
<i>18</i>&nbsp;    }
<b class="nc"><i>19</i>&nbsp;</b>
<b class="nc"><i>20</i>&nbsp;    public void evaluate() throws Exception {</b>
<b class="nc"><i>21</i>&nbsp;        boolean complete = false;</b>
<b class="nc"><i>22</i>&nbsp;</b>
<b class="nc"><i>23</i>&nbsp;        try {</b>
<b class="nc"><i>24</i>&nbsp;            this.next.evaluate();</b>
<b class="nc"><i>25</i>&nbsp;            complete = true;</b>
<i>26</i>&nbsp;        } catch (AssumptionViolatedException var4) {
<i>27</i>&nbsp;            throw var4;
<b class="nc"><i>28</i>&nbsp;        } catch (Throwable var5) {</b>
<i>29</i>&nbsp;            if(!this.expected.isAssignableFrom(var5.getClass())) {
<b class="nc"><i>30</i>&nbsp;                String message = &quot;Unexpected exception, expected&lt;&quot; + this.expected.getName() + &quot;&gt; but was&lt;&quot; + var5.getClass().getName() + &quot;&gt;&quot;;</b>
<b class="nc"><i>31</i>&nbsp;                throw new Exception(message, var5);</b>
<b class="nc"><i>32</i>&nbsp;            }</b>
<i>33</i>&nbsp;        }
<i>34</i>&nbsp;
<b class="nc"><i>35</i>&nbsp;        if(complete) {</b>
<i>36</i>&nbsp;            throw new AssertionError(&quot;Expected exception: &quot; + this.expected.getName());
<i>37</i>&nbsp;        }
<i>38</i>&nbsp;    }
<i>39</i>&nbsp;}
</div>
</div>

<div class="footer">
    
    <div style="float:right;">generated on 2014-12-21 15:48</div>
</div>
</body>
</html>
